apiVersion: v1
kind: Secret
metadata:
  name: fined-mentor-backend-secret
  labels:
    app: fined-mentor-backend
type: Opaque
data:
  JWT_SECRET: SGVsbG8gV29ybGQ=
  EMAIL_USERNAME: your_username_base64_encoded_here
  EMAIL_PASSWORD: your_password_base64_encoded_here
  GOOGLE_GENAI_API_KEY: your_google_genai_api_key_base64_encoded_here
  TAVILY_API_KEY: your_tavily_api_key_base64_encoded_here