apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fined-mentor-backend-monitor
  labels:
    release: prometheus
spec:
  jobLabel: job
  endpoints:
    - interval: 5s
      path: /actuator/prometheus
      port: metrics
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: fined-mentor-backend
      job: fined-mentor-backend-job